import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;

public class BuildCampaign extends HttpServlet{	
public void doGet(HttpServletRequest req,HttpServletResponse res)
	throws ServletException,IOException
	{
		res.setContentType("text/html");
		res.setHeader("Cache-Control","no-store");
		PrintWriter out=res.getWriter();
		HttpSession session=req.getSession(false);
		String aduser;
		aduser = (String)session.getValue("aduser");
		java.util.Date time_comp=new java.util.Date(System.currentTimeMillis()-20*60*1000);
		java.util.Date accessed=new java.util.Date(session.getLastAccessedTime());
		if(session==null||aduser==null||accessed.before(time_comp)){
			    session.invalidate();
			    out.println("<H2>Your Session has expired </H2>");
				out.println("<a href='admin.htm'>Click Here</a> To Re-Login");
				return;
		}
		out.println("<html>");
		out.println("<head>");
		out.println("<title></title>");
		out.println("</head>");
		out.println("<body topmargin='0' leftmargin='0' link='#FFFFFF' vlink='#FFFFFF' alink='#FFFFFF'>");
		out.println("<table border='0' width='100%' cellspacing='0' cellpadding='0' bgcolor='#000000' height='24'>");
		out.println("<tr>");
		out.println("<td width='42%' height='24'></td>");
		out.println("<td width='28%' height='24'></td>");
		out.println("<td width='5%' height='24'></td>");
		out.println("<td width='25%' height='24'></td>");
		out.println("</tr>");
		out.println("</table>");
		out.println("<div align='right'>");
		out.println("<table border='0' width='98%' cellspacing='0' cellpadding='0'>");
		out.println("<tr>");
		out.println("<td width='100%' height='10' colspan='2'></td>");
		out.println("</tr>");
		out.println("<tr>");
		out.println("<td width='100%' colspan='2'><strong><small><font face='Verdana'>Mail Blaster Contol Panel</font></small></strong></td>");
		out.println("</tr>");
		out.println("<tr>");
		out.println("<td width='64%' bgcolor='#C0C0C0' height='1'></td>");
		out.println("<td width='16%' bgcolor='#FFFFFF' height='1'></td>");
		out.println("</tr>");
		out.println("</table>");
		out.println("</div><div align='right'>");
		out.println("<table border='0' width='92%' height='20' cellspacing='0' cellpadding='0'>");
		out.println("<tr>");
		out.println("<td width='100%'></td>");
		out.println("</tr>");
		out.println("</table>");
		out.println("</div><div align='right'>");
		out.println("<table border='1' width='97%' bgcolor='#C0C0C0' bordercolor='#C0C0C0' cellspacing='0' cellpadding='0' bordercolorlight='#C0C0C0'>");
		out.println("<tr>");
		out.println("<td width='100%'><font face='Verdana' color='#FFFFFF'><small><strong>Create a New Campaign..</strong></small></font></td>");
		out.println("</tr>");
		out.println("</table>");
		out.println("</div><div align='right'>");
		out.println("<table border='1' width='97%' cellspacing='0' cellpadding='0' height='271' bordercolor='#COCOCO' bordercolorlight='#COCOCO'>");
		out.println("<tr>");
		out.println("<td width='100%' bgcolor='#F0F0FF' height='271' valign='top' align='center'><form method='POST' action='BuildCampaign2'  ENCTYPE='multipart/form-data'>");
		out.println("<table border='0' width='79%' cellspacing='0' cellpadding='0' height='161' <tr>");
		out.println("<tr>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'><small>Please Fill the form below to create a new campaign.</small></font></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'><small>&nbsp; Enter the name for your new campaign:</small></font></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'>&nbsp; <input type='text' name='camp_name' size='20'><small><font face='verdana'><small><small>*Maximum 25 chars</samll></small></font></small><br></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'><small>&nbsp;Enter the From Name Label:</small></font></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'>&nbsp; <input type='text' name='from_name' size='20'><small><font face='verdana'><small><small></samll></small></font></small></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'><small>Enter the From Email Label:</small></font></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'>&nbsp; <input type='text' name='from_email' size='20'><small><font face='verdana'><small><small></samll></small></font></small><br></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'><small>Enter the Subject of email:</small></font></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'>&nbsp; <input type='text' name='mail_subject' size='20'><small><font face='verdana'><small><small></samll></small></font></small><br></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'><small>Unsubscribe Field Required:</small></font></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'>&nbsp; <select name='unsubs_reqd'><option value='1'>Yes</option> <option value='0'>No</option> </select><font face='verdana'><small><small></samll></small></font></small><br></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'><small> Choose Your File Below:</small></font></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
	    out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'><input type='file' name='html_file'><br><td>");
	    out.println("</tr>");
	    /*out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'><small>Enter Your HTML Mail Below:</small></font></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'><textarea rows='15' name='html_data' cols='70'></textarea><br></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'><small>Enter Your Text Mail Below:</small></font></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'><textarea rows='15' name='text_data' cols='70'></textarea><br></td>");
		out.println("</tr>");
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><font face='Verdana' color='#000080'><small>Attach File</small></font></td>");
		out.println("</tr>");
	    out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><input type='file'  name='attach'></td>");
		out.println("</tr>");*/
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'></td>");
		out.println("</tr>");		
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'><input type='submit' value='Submit' name='B1' style='background-color: rgb(196,196,255); color: rgb(0,0,0); border: 1px solid rgb(0,0,128)'></td>");
		out.println("</tr>");		
		out.println("<tr align='center'>");
		out.println("<td width='100%' height='27' valign='top' align='left' colspan='2'></td>");
		out.println("</tr>");
		out.println("</table>");
		out.println("</form>");
		out.println("</td>");
		out.println("</tr>");
		out.println("</table>");
		out.println("</div>");
		out.println("</body>");
		out.println("</html>");
	}
}
	
	